### ISSUE TITLE
Android - Titanium 3.3.0 Force Close

### ISSUE THREAD

**Issue by ryanbuening** [manumaticx/Toasti#12]
Not sure if it is just me but since upgrading to Ti 3.3.0 SDK, when trying to do a  .show(), the app force closes on Android. Seems to be fine on iOS.

**Comment by manumaticx** [comment]
@rbuening28 I didn't test it with 3.3.0 because personally, I don't use Toasti anymore in favor of TiCrouton. There where massive changes in the Titanium SDK in 3.2.0 and 3.3.0 according to heavyweight windows on Android. Toasti was originally based on lightweight windows. Since they were removed it's pretty useless on Android (IMHO) - I don't like the fact that a notification needs to appear in its own Activity.

Anyway, if you have a fix for this bug, I would be glad if you send me a pull request.

**Comment by ryanbuening** [comment]
Thanks for the reply. I am going to try TiCrouton.
